name: Deploy to GCP App Engine

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Enter branch to deploy"
        required: true
        default: "main"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      AUTH0_SECRET: ${{secrets.AUTH0_SECRET}}
      AUTH0_BASE_URL: ${{secrets.AUTH0_BASE_URL}}
      AUTH0_ISSUER_BASE_URL: ${{secrets.AUTH0_ISSUER_BASE_URL}}
      AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
      DATABASE_DEV_URL: ${{secrets.DATABASE_DEV_URL}}
      UPSTASH_REDIS_REST_URL: ${{secrets.UPSTASH_REDIS_REST_URL}}
      UPSTASH_REDIS_REST_TOKEN: ${{secrets.UPSTASH_REDIS_REST_TOKEN}}
    steps:
      - id: checkout
        name: Action Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.inputs.branch}}
      - id: node-setup
        name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - id: install-dependencies
        name: Install Node Dependencies
        run: npm install
      - id: build-app
        name: Build App
        run: npm run build
      - id: auth
        name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}
      - id: "Deploy"
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: trans-setup-410915
          deliverables: app.yaml
